<a href="https://colab.research.google.com/github/nichakornchaisuwan/multivariaet/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Function


```python
def function_name(_Input_):
    do_something with _Input_ to produce _Output_
    return _Output_
```



function มีส่วนสำคัญทั้งหมด 4 ส่วน

1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)
2. กำหนดตัวแปรที่จะเป็น input *Input* (ขาดได้)
3. ส่วนประมวลผล do_something with Input to get Output (ขาดไม่ได้)
4. ส่วน output return Output(ขาดได้)

เราใช้ เว้นวรรค (indent) เพื่อบอกขอบเขตของ code

สร้างฟังก์ชั่น

In [ ]:
def print_name(name,surname,ID):
    st=f'ชื่อ {name} นามสกุล {surname} ID {ID}' #การสร้างฟังก์ชั่น
    return st
print('outside function')

outside function


การเรียกใช้ฟังก์ชั่น

In [ ]:
print_name('กิตติมา','อุปสุข','623021040-9') #การเรียกใช้

'ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9'

In [ ]:
output_string = print_name('กิตติมา','อุปสุข','623021040-9')
print(output_string)

ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9


ฟังก์ชั่นไม่จำเป็นต้องมร Output

In [ ]:
def print_name2(surname,ID,name):
    st=f'ชื่อ {name} นามสกุล {surname} ID {ID}' #ฟังก์ชั่นไม่จำเป็นต้องมี output
    print(st)

In [ ]:
print_name2('กิตติมา','อุปสุข','623021040-9')

ชื่อ 623021040-9 นามสกุล กิตติมา ID อุปสุข


In [ ]:
op2 = print_name2('กิตติมา','อุปสุข','623021040-9')

ชื่อ 623021040-9 นามสกุล กิตติมา ID อุปสุข


In [ ]:
print(op2)

None


ฟังก์ชั่นไม่จำเป็นต้องมี Input

In [ ]:
def Pi():
    return 3.14159265359

In [ ]:
Pi()*(1.5**2) # คำนวนพื้นที่วงกลมที่มีขนาดเส้นผ่าศูนย์กลางเท่ากับ 3 

7.0685834705775

In [ ]:
def print_my_name():
    print('ณิชากร ไชยสุวรรณ ID 623020521-8')

In [ ]:
print_my_name()

ณิชากร ไชยสุวรรณ ID 623020521-8


# input ของฟังก์ชั่นใน python มี 2 แบบ
จำเป็นต้องใส่ 

ไม่จำเป็นต้องใส่ (มีค่า default)

โดยเราจะเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name,surname,ID,grade='F'):
    st = f'= ชื่อ {name} นามสกุล {surname} ID {ID}'
    print(st)
    st2 = f'เกรดวิชา Multivariate >>>{grade}'
    print(st2)

In [ ]:
print_2lines_default('ภิญญาดา','เพ็ญสุข','623021052-2')

= ชื่อ ภิญญาดา นามสกุล เพ็ญสุข ID 623021052-2
เกรดวิชา Multivariate >>>F


In [ ]:
print_2lines_default('ภิญญาดา','เพ็ญสุข','623021052-2','A')

= ชื่อ ภิญญาดา นามสกุล เพ็ญสุข ID 623021052-2
เกรดวิชา Multivariate >>>A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

In [ ]:
print_name2(name='กิตติมา',surname='อุปสุข', ID='623021040-9')

ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9


#**HW3 ให้เขียน function คำนวณจำนวนวินาทีจากเวลาต่อไปนี้ และ printให้สวยงาม**

Q1. '14-15-31'

Q2. '13-00-01'

Q3. '05-49-44'

# Q4. '00-00-16'

In [ ]:
def time(t):
  time_sp = t.split('-')
  h1=int (time_sp[0])*3600
  m1=int (time_sp[1])*60
  s1=int (time_sp[2])*1
  Ans = h1+m1+s1
  print(f'เวลา {t} สามารถแปลงได้เป็น {Ans} วินาที')

In [ ]:
time ('14-15-31')

เวลา 14-15-31 สามารถแปลงได้เป็น 51331 วินาที


In [ ]:
time('13-00-01')

เวลา 13-00-01 สามารถแปลงได้เป็น 46801 วินาที


In [ ]:
time ('05-49-44')

เวลา 05-49-44 สามารถแปลงได้เป็น 20984 วินาที


In [ ]:
time ('00-00-16')

เวลา 00-00-16 สามารถแปลงได้เป็น 16 วินาที


#**Numpy** -> package (สำหรับจัดการกับ Array ที่เป็นตัวเลข Matrix)

Num+py -> Number-Numerical + python

การใช้ package 

1.``` Import``` ``` ชื่อ package``` # 
2. ``` ชื่อ package.```




In [1]:
import numpy

data structure -> array

สร้าง array (numpy array)

In [3]:
max_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(max_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [5]:
max_ex1[1,1] #ข้างหน้า, คือแถว ข้างหลัง, คือหลัก (การระบุค่าของ แมทริกซ์)

0.1

ถ้าไม่มี numpy array 

In [6]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [8]:
list_ex1[1][1] 

0.1

In [10]:
print(list_ex1)
a=list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix operation

data 2 แบบ ->
matrix (2D array) 

In [13]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกกับ

In [14]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


การตรวจสอบขนาดของ matrix

In [15]:
mat_ex3.shape

(2, 3)

In [16]:
mat_ex3.shape[0]

2

# คูณ *matrix*

แถวคูณหลัก 

หลักของ matrix ตัวข้างหน้า ต้องเท่ากับแถวของmatrix ของตัวข้างหลัง

dot product (AAA,x),(x,BBB) = (AAA,BBB)

In [17]:
mat_ex1*mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [18]:
numpy.dot(mat_ex1,mat_ex2)

ValueError: ignored

In [19]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


#Transpose กลับแถวเป็นหลัก กลับหลักเป็นแถว


``` matrix.T```



In [21]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [20]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [23]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])